version: '3'
services:
  app:
    image: openjdk:10
    container_name: tw-modoki-app
    ports:
      - 8090:8080
    links:
      - db
    volumes:
      - .:/app
      - ~/.config/:/root/.config
    working_dir: /app
    command: ./gradlew bootRun
  db:
    image: mysql:5.7
    container_name: tw-modoki-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
