version: '3'
services:
  app:
    image: openjdk:10
    container_name: tw-modoki-app
    ports:
      - 8090:8080
    links:
      - db
    volumes:
      - .:/app
      - ~/.config/:/root/.config
    working_dir: /app
    command: ./gradlew bootRun
  db:
    image: mysql:5.7
    container_name: tw-modoki-db
    restart: always
    environment:
      MYSQL_DATABASE: twitter_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - ./infra/docker/mysql/db/data:/var/lib/mysql
      - ./infra/docker/mysql/conf.d:/etc/mysql/conf.d
      - ./infra/docker/mysql/initdb.d:/docker-entrypoint-initdb.d